name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ### meta
          API_BASE_URL: https://wakatime.com/api # optional
          ### content
          SHOW_TITLE: true # optional
          SECTION_NAME: waka # Section name in the README
          TIME_RANGE: all_time # Time range for metrics (e.g., last_7_days, last_30_days, etc.)
          LANG_COUNT: 15 # Number of languages to show
          SHOW_TIME: true # Show time spent on each item
          SHOW_TOTAL: true # Show total time
          IGNORED_LANGUAGES: YAML JSON TOML # Languages to ignore in the report
          ### commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics # optional
          TARGET_BRANCH: main # optional
          TARGET_PATH: README.md # optional
          COMMITTER_NAME: GitHubActionBot # optional
          COMMITTER_EMAIL: action-bot@github.com # optional
          AUTHOR_NAME: dappsar # optional
          AUTHOR_EMAIL: dapps.ar@gmail.com # optional
          # you can populate email-id with secrets instead
